#!name=BeiZi
#!desc=BeiZi去广告

[Rule]

# beizi
DOMAIN-SUFFIX,beizi.biz,REJECT
DOMAIN-SUFFIX,8ziben.com,REJECT

# adukwai
DOMAIN-SUFFIX,adukwai.com,REJECT

# zijieapi
DOMAIN,api-access.pangolin-sdk-toutiao.com,REJECT
DOMAIN,api-access.pangolin-sdk-toutiao1.com,REJECT
DOMAIN,log-api.pangolin-sdk-toutiao.com,REJECT
DOMAIN,log-api.pangolin-sdk-toutiao-b.com,REJECT
DOMAIN,gromore.pangolin-sdk-toutiao.com,REJECT
DOMAIN,p9-be-pack-sign.pglstatp-toutiao.com,REJECT
DOMAIN,sf3-fe-tos.pglstatp-toutiao.com,REJECT
DOMAIN,mon.zijieapi.com,REJECT
DOMAIN,tnc11-bjlgy.zijieapi.com,REJECT
DOMAIN,tnc3-bjlgy.zijieapi.com,REJECT
DOMAIN,tnc3-alisc1.zijieapi.com,REJECT
DOMAIN,tnc11-bjlgy.bytedance.com,REJECT
DOMAIN,tnc3-bjlgy.bytedance.com,REJECT

# other
DOMAIN,ad.data.lianjia.com,REJECT
DOMAIN,adsmind.ugdtimg.com,REJECT
DOMAIN,pgdt.ugdtimg.com,REJECT
DOMAIN,i.gtimg.cn,REJECT
DOMAIN,configure.rayjump.com,REJECT
DOMAIN,gdfp.gifshow.com,REJECT
DOMAIN,images.pinduoduo.com,REJECT
DOMAIN,open.e.kuaishou.com,REJECT
DOMAIN,toblog.ctobsnssdk.com,REJECT
# ZJAdSDK初始化入口
DOMAIN,static.luckas.cn,REJECT
